### ISSUE TITLE
About supp

### ISSUE THREAD

**Issue by guanjunwu** [dreamscene4d/dreamscene4d#1]
Hi, thanks for your great work! I'm impressed by the good result very much!
Besides, I'm wondering where is the supplementary file. Could you share a link?
by the way, I'm waiting for your code !!!

**Comment by lkeab** [comment]
Thanks for your attention. We will update our arXiv to include the Supp. file in next 2/3 weeks. Also, we will release code in June.

**Comment by lkeab** [comment]
hi, we updated our arXiv :)

**Comment by guanjunwu** [comment]
great! Thank you again!!!
