### ISSUE TITLE
No module named 'deva.dataset'

### ISSUE THREAD

**Issue by hywang2002** [dreamscene4d/dreamscene4d#6]
hi, thank you for your wonderful work, in ./trackseg/deva/inference/demo_utils.py, not found deva.dataset.utils
![image](https://github.com/user-attachments/assets/086d9c75-0718-409c-8c06-2f8516de6c79)

**Comment by sbsws88** [comment]
Hi @hywang2002

Could you resolve this problem?

**Comment by hywang2002** [comment]
> Hi @hywang2002
> 
> Could you resolve this problem?

hi, I commented out this line and the line 12 'image = im_normalization(image)' and the codes works fine.
